version: '3'
services:
  ukc-ep:
    image: "unboundukc/ukc-vhsm:${CASP_VERSION:-latest}"
    container_name: ukc-ep
    restart: always
    ports:
     - "8443:8443"
    command: ["ep", "ukc-partner", "ukc-aux"] 
    hostname: ukc-ep
    environment:
      UKC_NOCERT: 'true'
      UKC_PASSWORD: 'Unbound1!'
      UKC_PARTITION: 'casp'
      UKC_PARTITION_USER_PASSWORD: 'Unbound1!'
  ukc-partner:
    image: "unboundukc/ukc-vhsm:${CASP_VERSION:-latest}"
    container_name: ukc-partner
    restart: always
    command: ["partner", "ukc-ep", "ukc-aux"]
    hostname: ukc-partner
  ukc-aux:
    image: "unboundukc/ukc-vhsm:${CASP_VERSION:-latest}"
    container_name: ukc-aux
    restart: always
    command: ["aux", "ukc-ep", "ukc-partner"]
    hostname: ukc-aux
    depends_on:
      - "ukc-ep"
      - "ukc-partner"
  db:
    image: postgres:11
    container_name: db
    restart: always
    ports:
      - 5432:5432
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: 'DBPassword'
  casp:
    image: "unboundcasp/casp:${CASP_VERSION:-latest}"
    container_name: casp
    restart: always
    ports:
      - "443:443"
    environment:
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGUSER: 'postgres'
      PGPASSWORD: 'DBPassword'
      UKC_EP: 'ukc-ep'
      UKC_PARTITION: 'casp'
      UKC_PARTITION_USER_PASSWORD: 'Unbound1!'
      CASP_FIREBASE_TOKEN: ${FIREBASE_TOKEN}
      INFURA_TOKEN: ${INFURA_TOKEN}
      BLOCKCYPHER_TOKEN: ${BLOCKCYPHER_TOKEN}
      CASP_SO_PASSWORD: 'Unbound1!'
      CASP_ACCOUNT: 'CASP'
    depends_on:
      - "ukc-ep"
      - "ukc-partner"
      - "ukc-aux"
      - "db"
  casp-bot:
    image: "unboundcasp/casp-bot:${CASP_VERSION:-latest}"
    container_name: casp-bot
    restart: always
    environment:
      BOT_NAME: 'casp-bot'
      CASP: 'casp'
      CASP_SO_PASSWORD: 'Unbound1!'
      CASP_ACCOUNT: 'CASP'
    depends_on:
      - "casp"
      